apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: indiana-ingress
  namespace: indiana
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: indiana-huha-test.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: {{ .Values.indiana.serviceName }}
          servicePort: 8000