apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: indiana-ingress
  namespace: indiana
spec:
  rules:
  - host: indiana-test.com
    http:
      paths:
      - backend:
          serviceName: {{ .Values.indiana.serviceName }}
          servicePort: 8000