apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.indiana.serviceName }}
spec:
  selector:
    app: {{ .Values.indiana.serviceName }}
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30100
  type: NodePort
